/* eslint-disable import/prefer-default-export */

/**
 * Leesbare omschrijvingen voor alle 48 faultcodes die het apparaat kan rapporteren.
 * Sleutel = faultcode zoals teruggegeven door DataSnapshot.status.activeFaults.
 */
export const FAULT_DESCRIPTIONS: Record<string, string> = {
  FAULT_1_BIT0: 'Phase sequence error / missing phase',
  FAULT_1_BIT1: 'Water flow switch alarm',
  FAULT_1_BIT2: 'High pressure alarm',
  FAULT_1_BIT3: 'Low pressure alarm',
  FAULT_1_BIT4: 'Compressor over-current alarm',
  FAULT_1_BIT5: 'Module temperature alarm',
  FAULT_1_BIT6: 'Ambient sensor (T1) alarm',
  FAULT_1_BIT7: 'Outer coil sensor (T2) alarm',
  FAULT_1_BIT8: 'Inner coil sensor (T3) alarm',
  FAULT_1_BIT9: 'Suction sensor (T4) alarm',
  FAULT_1_BIT10: 'Exhaust sensor (T5) alarm',
  FAULT_1_BIT11: 'Water inlet sensor (T6) alarm',
  FAULT_1_BIT12: 'Water outlet sensor (T7) alarm',
  FAULT_1_BIT13: 'Economizer inlet (T8) alarm',
  FAULT_1_BIT14: 'Economizer outlet (T9) alarm',
  FAULT_1_BIT15: 'DHW tank sensor alarm',
  FAULT_2_BIT0: 'Environment humidity alarm',
  FAULT_2_BIT1: 'Plate heat exchanger sensor alarm',
  FAULT_2_BIT2: 'Buffer tank sensor alarm',
  FAULT_2_BIT3: 'Water pump 1 alarm',
  FAULT_2_BIT4: 'Water pump 2 alarm',
  FAULT_2_BIT5: 'Zone 1 mixing valve alarm',
  FAULT_3_BIT0: 'Expansion board communication alarm',
  FAULT_3_BIT1: 'Fan motor 1 alarm',
  FAULT_3_BIT2: 'Fan motor 2 alarm',
  FAULT_3_BIT3: 'Fan motor 3 alarm',
  FAULT_3_BIT4: 'Fan motor 4 alarm',
  FAULT_3_BIT5: 'Model mismatch alarm',
  FAULT_3_BIT6: 'Controller communication alarm',
  FAULT_3_BIT7: 'Zone 2 mixing valve alarm',
  FAULT_3_BIT8: 'DHW return sensor alarm',
  FAULT_3_BIT9: 'Total outlet sensor alarm',
  FAULT_3_BIT10: 'Zone 1 mixing sensor alarm',
  SYS1_FAULT_1_BIT0: 'Compressor high-temp protection',
  SYS1_FAULT_1_BIT1: 'Compressor low-temp protection',
  SYS1_FAULT_1_BIT2: 'Discharge high-pressure protection',
  SYS1_FAULT_1_BIT3: 'Suction low-pressure protection',
  SYS1_FAULT_1_BIT4: 'Compressor over-current protection',
  SYS1_FAULT_1_BIT5: 'IPM over-temperature protection',
  SYS1_FAULT_1_BIT6: 'AC input over-voltage protection',
  SYS1_FAULT_1_BIT7: 'AC input under-voltage protection',
  SYS1_FAULT_1_BIT8: 'DC bus over-voltage protection',
  SYS1_FAULT_1_BIT9: 'DC bus under-voltage protection',
  SYS1_FAULT_1_BIT10: 'Compressor start failure',
  SYS1_FAULT_1_BIT11: 'Communication alarm (controller)',
  SYS1_FAULT_1_BIT12: 'Phase current imbalance',
  SYS1_FAULT_1_BIT13: 'Drive over-current alarm',
  SYS1_FAULT_1_BIT14: 'Ground fault alarm',
};
